---
 - name: "installing git and tree"
   hosts: all
   become: true
   tasks:
    - name: "terraform commands"
      displayname: 'terraform init'
      inputs:
          script: sh 'terraform init'
    - name: "terraform commands"
      displayname: 'terraform format'
      inputs:
          script: sh 'terraform fmt'
    - name: "terraform commands"
      displayname: 'terraform validate'
      inputs:
          script: sh 'terraform validate'

    - name: "git installing"
      yum:
       name: git
       state: true
       command: systemctl start git
    - name: "installing tree"
      yum:
       name: tree
       state: present
...
